version: "3.8"

services:
  api:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trainerfinder_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  postgres_data_prod:
