version: "3.8"

services:
  api:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - .env.staging
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trainerfinder_staging
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_staging:
